In [ ]:
import pandas as pd
import numpy as np
import nltk

from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report


nltk.download('twitter_samples')

[nltk_data] Downloading package twitter_samples to
[nltk_data]     /Users/periadhityan/nltk_data...
[nltk_data]   Package twitter_samples is already up-to-date!

True

In [40]:
df = pd.read_csv('amazon.csv')
df

                                              reviewText  Positive
0      This is a one of the best apps acording to a b...         1
1      This is a pretty good version of the game for ...         1
2      this is a really cool game. there are a bunch ...         1
3      This is a silly game and can be frustrating, b...         1
4      This is a terrific game on any pad. Hrs of fun...         1
...                                                  ...       ...
19995  this app is fricken stupid.it froze on the kin...         0
19996  Please add me!!!!! I need neighbors! Ginger101...         1
19997  love it!  this game. is awesome. wish it had m...         1
19998  I love love love this app on my side of fashio...         1
19999  This game is a rip off. Here is a list of thin...         0

[20000 rows x 2 columns]

In [7]:
# create preprocess_text function

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

def preprocess_text(text):
    tokens = word_tokenize(text.lower())
    filtered_tokens = [token for token in tokens if token not in stopwords.words('english')]
    lemmatizer = WordNetLemmatizer()
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in filtered_tokens]
    processed_text = ' '.join(lemmatized_tokens)
    return processed_text

# initialize NLTK sentiment analyzer

from nltk.sentiment.vader import SentimentIntensityAnalyzer

analyzer = SentimentIntensityAnalyzer()

def get_sentiment(text):
    scores = analyzer.polarity_scores(text)
    sentiment = 1 if scores['pos'] > 0 else 0
    return sentiment

num_pos = df['Positive'].value_counts()[1]
num_neg = df['Positive'].value_counts()[0]

print(num_pos)
print(num_neg)

most_freq_class = 1

15233
4767

In [12]:


import pandas as pd
df = pd.read_csv('amazon.csv')
text = preprocess_text(df['reviewText'][1])

from nltk.sentiment.vader import SentimentIntensityAnalyzer
SentimentIntensityAnalyzer().polarity_scores(text)

{'neg': 0.0, 'neu': 0.318, 'pos': 0.682, 'compound': 0.9325}

In [39]:
df

                                              reviewText  Positive  sentiment
0      one best apps acording bunch people agree bomb...         1          1
1      pretty good version game free . lot different ...         1          1
2      really cool game . bunch level find golden egg...         1          1
3      silly game frustrating , lot fun definitely re...         1          1
4      terrific game pad . hr fun . grandkids love . ...         1          1
...                                                  ...       ...        ...
19995  app fricken stupid.it froze kindle wont allow ...         0          1
19996  please add ! ! ! ! ! need neighbor ! ginger101...         1          1
19997  love ! game . awesome . wish free stuff house ...         1          1
19998  love love love app side fashion story fight wo...         1          1
19999  game rip . list thing make better & bull ; fir...         0          1

[20000 rows x 3 columns]

In [1]:
df_mostfreq = df
df_mostfreq['reviewText'] = df['reviewText'].apply(preprocess_text)
df_mostfreq['sentiment'] = most_freq_class
print(confusion_matrix(df['Positive'], df['sentiment']))

NameError: name 'df' is not defined

In [7]:

df['reviewText'] = df['reviewText'].apply(preprocess_text)
df['sentiment'] = df['reviewText'].apply(get_sentiment)

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

print(confusion_matrix(df['Positive'], df['sentiment']))
print(classification_report(df['Positive'], df['sentiment']))

[[ 1131  3636]
 [  576 14657]]
              precision    recall  f1-score   support

           0       0.66      0.24      0.35      4767
           1       0.80      0.96      0.87     15233

    accuracy                           0.79     20000
   macro avg       0.73      0.60      0.61     20000
weighted avg       0.77      0.79      0.75     20000

In [30]:
df2  = pd.read_csv('WAZE_REVIEWS.csv')
df2 = df2.iloc[0:25001]
df2 = df2[['review_text', 'review_rating']]
df2 = df2.rename(columns={'review_text' : 'reviewText', 'review_rating' : 'Positive'})
df2['Positive'] = np.where(df2['Positive'] <= 2 , 0, df2['Positive'])
df2['Positive'] = np.where(df2['Positive'] >= 3, 1, df2['Positive'])
df2 = df2[df2['reviewText'].apply(lambda x: isinstance(x, str))]

In [9]:
df2['reviewText'] = df2['reviewText'].apply(preprocess_text)
df2['sentiment'] = df2['reviewText'].apply(get_sentiment)
print(confusion_matrix(df2['Positive'], df2['sentiment']))
print(classification_report(df2['Positive'], df2['sentiment']))

[[  943   931]
 [ 4137 18989]]
              precision    recall  f1-score   support

           0       0.19      0.50      0.27      1874
           1       0.95      0.82      0.88     23126

    accuracy                           0.80     25000
   macro avg       0.57      0.66      0.58     25000
weighted avg       0.90      0.80      0.84     25000

In [43]:
all_positive_tweets = twitter_samples.strings('positive_tweets.json')
all_negative_tweets = twitter_samples.strings('negative_tweets.json')
all_positive_tweets = pd.DataFrame(all_positive_tweets)
all_negative_tweets = pd.DataFrame(all_negative_tweets)

all_positive_tweets['Positive'] = 1
all_negative_tweets['Positive'] = 0

all_positive_tweets = all_positive_tweets.rename(columns={ 0 : 'Text'})
all_negative_tweets = all_negative_tweets.rename(columns={ 0 : 'Text'})

frames = [all_positive_tweets, all_negative_tweets]
all_tweets = pd.concat(frames)

all_tweets

                                                   Text  Positive
0     #FollowFriday @France_Inte @PKuchly57 @Milipol...         1
1     @Lamb2ja Hey James! How odd :/ Please call our...         1
2     @DespiteOfficial we had a listen last night :)...         1
3                                  @97sides CONGRATS :)         1
4     yeaaaah yippppy!!!  my accnt verified rqst has...         1
...                                                 ...       ...
4995               I wanna change my avi but uSanele :(         0
4996                         MY PUPPY BROKE HER FOOT :(         0
4997           where's all the jaebum baby pictures :((         0
4998  But but Mr Ahmad Maslan cooks too :( https://t...         0
4999  @eawoman As a Hull supporter I am expecting a ...         0

[10000 rows x 2 columns]

In [38]:
all_tweets['Text'] = all_tweets['Text'].apply(preprocess_text)
all_tweets['sentiment'] = all_tweets['Text'].apply(get_sentiment)
print(confusion_matrix(all_tweets['Positive'], all_tweets['sentiment']))
print(classification_report(all_tweets['Positive'], all_tweets['sentiment']))

[[2887 2113]
 [1754 3246]]
              precision    recall  f1-score   support

           0       0.62      0.58      0.60      5000
           1       0.61      0.65      0.63      5000

    accuracy                           0.61     10000
   macro avg       0.61      0.61      0.61     10000
weighted avg       0.61      0.61      0.61     10000

In [42]:
all_tweets

                                                   Text  Positive  sentiment
0     # followfriday @ france_inte @ pkuchly57 @ mil...         1          1
1     @ lamb2ja hey james ! odd : / please call cont...         1          1
2     @ despiteofficial listen last night : ) bleed ...         1          1
3                                @ 97sides congrats : )         1          1
4     yeaaaah yippppy ! ! ! accnt verified rqst succ...         1          1
...                                                 ...       ...        ...
4995                      wan na change avi usanele : (         0          0
4996                               puppy broke foot : (         0          0
4997                       's jaebum baby picture : ( (         0          0
4998  mr ahmad maslan cook : ( http : //t.co/arcid31zv6         0          0
4999  @ eawoman hull supporter expecting misserable ...         0          1

[10000 rows x 3 columns]